channels:
  - bioconda
  - conda-forge
  - r
  - defaults
  - pyvizhttps://github.com/Ally-Vella/Blender/blob/master/environment.yml
dependencies:
  - hvplot
  - jupyter
  - notebook
  - seaborn
  - jupyter-panel-proxy
